name: Deploy Odoo to EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar tu codigo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Conectarse a Docker Hub
     # - name: Login to Docker Hub
      #  uses: docker/login-action@v2
       # with:
         # username: ${{ secrets.DOCKER_USERNAME }}
        #  password: ${{ secrets.DOCKER_PASSWORD }} 

      # 3. Construir la imagen y subirla
      #- name: Build and push Docker image
      #  uses: docker/build-push-action@v4
       # with:
        #  context: .
         # push: true
          # CORRECCION IMPORTANTE: El nombre exacto de tu repo en Docker Hub
          #tags: ${{ secrets.DOCKER_USERNAME }}/odoo-docker-reto2:latest

      # 4. Desplegar en EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        # Pasamos el secreto como variable de entorno
        env:
          PG_PASS: ${{ secrets.PG_PASSWORD_VALUE }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          # Enviamos la variable al servidor
          envs: PG_PASS
          script: |
            # Crear carpeta si no existe
            mkdir odoo
            cd odoo
            git init
            git remote add origin https://github.com/nsmirnitskii-hue/Odoo-Docker.git
            git pull origin main
            cd Odoo-Docker
            
            # Usar la variable secreta para crear el archivo
            echo "$PG_PASS" > postgresql_password
            
            # Parar contenedores viejos
            docker-compose down || true           
               
            # Actualizar y arranca
            docker-compose up -d